# MQTT Agent Hub env names
ENV_MQTT_BROKER_HOST = "MQTT_BROKER_HOST"
ENV_MQTT_BROKER_PORT = "MQTT_BROKER_PORT"
ENV_MQTT_HUB_TOKEN = "MQTT_HUB_TOKEN"
ENV_MQTT_WS_PORT = "MQTT_WS_PORT"
ENV_HUB_PORT = "HUB_PORT"
ENV_AGENT_VERSION = "AGENT_VERSION"
ENV_LLM_PATH = "LLM_PATH"
ENV_TELEMETRY_INTERVAL = "TELEMETRY_INTERVAL"

# ---------------------------------------------------------------------------
# Doc Ingest / RAG pipeline env names
# ---------------------------------------------------------------------------

# LLM / llama-cpp
ENV_LLAMA_N_CTX = "LLAMA_N_CTX"
ENV_LLAMA_N_BATCH = "LLAMA_N_BATCH"
ENV_LLAMA_N_GPU_LAYERS = "LLAMA_N_GPU_LAYERS"
ENV_LLAMA_N_THREADS = "LLAMA_N_THREADS"
ENV_LLAMA_SEED = "LLAMA_SEED"
ENV_LLAMA_VERBOSE = "LLAMA_VERBOSE"
ENV_LLAMA_TEMPERATURE = "LLAMA_TEMPERATURE"
ENV_LLAMA_TOP_K = "LLAMA_TOP_K"
ENV_LLAMA_TOP_P = "LLAMA_TOP_P"
ENV_LLAMA_REPEAT_PENALTY = "LLAMA_REPEAT_PENALTY"
ENV_LLAMA_MAX_TOKENS = "LLAMA_MAX_TOKENS"
ENV_LLAMA_REMOTE_TIMEOUT = "LLAMA_REMOTE_TIMEOUT"
ENV_LLAMA_CHAT_FORMAT = "LLAMA_CHAT_FORMAT"
ENV_LLAMA_F16_KV = "LLAMA_F16_KV"

# Lifecycle folders
ENV_DEFAULT_DOC_INGEST_ROOT = "DEFAULT_DOC_INGEST_ROOT"
ENV_STAGING_DIR = "STAGING_DIR"
ENV_PREPROCESSING_DIR = "PREPROCESSING_DIR"
ENV_INGESTION_DIR = "INGESTION_DIR"
ENV_CONSUMING_DIR = "CONSUMING_DIR"
ENV_SUCCESS_DIR = "SUCCESS_DIR"
ENV_FAILED_DIR = "FAILED_DIR"

# Model paths / endpoints
ENV_EMBEDDING_ENDPOINTS = "EMBEDDING_ENDPOINTS"
ENV_TOKENIZER_MODEL_PATH = "TOKENIZER_MODEL_PATH"
ENV_SUPERVISOR_LLM_ENDPOINTS = "SUPERVISOR_LLM_ENDPOINTS"
ENV_WHISPER_MODEL_ENDPOINTS = "WHISPER_MODEL_ENDPOINTS"

# Supervisor LLM
ENV_SUPERVISOR_REMOTE_MODEL_NAME = "SUPERVISOR_REMOTE_MODEL_NAME"
ENV_SUPERVISOR_TEMPERATURE = "SUPERVISOR_TEMPERATURE"
ENV_SUPERVISOR_TOP_K = "SUPERVISOR_TOP_K"
ENV_SUPERVISOR_MAX_TOKENS = "SUPERVISOR_MAX_TOKENS"
ENV_SUPERVISOR_N_CTX = "SUPERVISOR_N_CTX"

# Storage
ENV_GATEKEEPER_FAILURE_DB = "GATEKEEPER_FAILURE_DB"
ENV_PARQUET_FILE = "PARQUET_FILE"
ENV_DUCKDB_FILE = "DUCKDB_FILE"

# Redis
ENV_REDIS_HOST = "REDIS_HOST"
ENV_REDIS_PORT = "REDIS_PORT"
ENV_REDIS_OCR_JOB_QUEUE = "REDIS_OCR_JOB_QUEUE"
ENV_REDIS_WHISPER_JOB_QUEUE = "REDIS_WHISPER_JOB_QUEUE"
ENV_REDIS_INGEST_QUEUE = "REDIS_INGEST_QUEUE"
ENV_REDIS_STAGING_QUEUE = "REDIS_STAGING_QUEUE"
ENV_QUEUE_NAMES = "QUEUE_NAMES"

# Vector DB
ENV_VECTOR_DB_PROFILE = "VECTOR_DB_PROFILE"
ENV_VECTOR_DB_URL = "VECTOR_DB_URL"
ENV_VECTOR_DB_HOST = "VECTOR_DB_HOST"
ENV_VECTOR_DB_PORT = "VECTOR_DB_PORT"
ENV_VECTOR_DB_GRPC_PORT = "VECTOR_DB_GRPC_PORT"
ENV_VECTOR_DB_USE_GRPC = "VECTOR_DB_USE_GRPC"
ENV_VECTOR_DB_COLLECTION = "VECTOR_DB_COLLECTION"
ENV_VECTOR_DB_BATCH_SIZE = "VECTOR_DB_BATCH_SIZE"
ENV_VECTOR_DB_TIMEOUT = "VECTOR_DB_TIMEOUT"

# Legacy Chroma aliases
ENV_CHROMA_HOST = "CHROMA_HOST"
ENV_CHROMA_PORT = "CHROMA_PORT"
ENV_CHROMA_COLLECTION = "CHROMA_COLLECTION"
ENV_MAX_CHROMA_BATCH_SIZE = "MAX_CHROMA_BATCH_SIZE"

# Chunking / ingestion
ENV_STAGED_CHUNK_TTL = "STAGED_CHUNK_TTL"
ENV_CONSUMER_BATCH_SIZE = "CONSUMER_BATCH_SIZE"
ENV_MAX_CHUNKS = "MAX_CHUNKS"
ENV_MAX_TOKENS = "MAX_TOKENS"
ENV_CHUNK_SIZE = "CHUNK_SIZE"
ENV_CHUNK_OVERLAP = "CHUNK_OVERLAP"

# Text / encoding
ENV_ALLOW_LATIN_EXTENDED = "ALLOW_LATIN_EXTENDED"
ENV_LATIN_SCRIPT_MIN_RATIO = "LATIN_SCRIPT_MIN_RATIO"

# OCR
ENV_OCR_ENDPOINTS = "OCR_ENDPOINTS"
ENV_DEBUG_IMAGE_DIR = "DEBUG_IMAGE_DIR"
ENV_MAX_OCR_DIM = "MAX_OCR_DIM"

# Load balancing
ENV_HA_INTERLEAVE = "HA_INTERLEAVE"

# File extensions
ENV_SUPPORTED_MEDIA_EXT = "SUPPORTED_MEDIA_EXT"

# Hardware / compute
ENV_DEVICE = "DEVICE"
ENV_COMPUTE_TYPE = "COMPUTE_TYPE"

# Batch sizes
ENV_EMBEDDING_BATCH_SIZE = "EMBEDDING_BATCH_SIZE"
ENV_MEDIA_BATCH_SIZE = "MEDIA_BATCH_SIZE"

# Retrieval
ENV_RETRIEVER_TOP_K = "RETRIEVER_TOP_K"

# Gatekeeper
ENV_GATEKEEPER_BATCH_SIZE = "GATEKEEPER_BATCH_SIZE"

# PDF processing
ENV_PDF_FORCE_OCR = "PDF_FORCE_OCR"
ENV_FORCE_MARKDOWN_LLM = "FORCE_MARKDOWN_LLM"

# Stuck job recovery
ENV_STUCK_JOB_TIMEOUT_HOURS = "STUCK_JOB_TIMEOUT_HOURS"

# Metrics
ENV_METRICS_ENABLED = "METRICS_ENABLED"
ENV_METRICS_LOG_FILE = "METRICS_LOG_FILE"
ENV_METRICS_LOG_TO_STDOUT = "METRICS_LOG_TO_STDOUT"

# File tracking
ENV_FAILED_FILES = "FAILED_FILES"
ENV_INGESTED_FILE = "INGESTED_FILE"

# Chat session
ENV_MAX_SESSION_TURNS = "MAX_SESSION_TURNS"
ENV_SESSION_TTL_HOURS = "SESSION_TTL_HOURS"

# NiFi
ENV_NIFI_ENDPOINT = "NIFI_ENDPOINT"
ENV_NIFI_SSL_VERIFY = "NIFI_SSL_VERIFY"
ENV_NIFI_USERNAME = "NIFI_USERNAME"
ENV_NIFI_PASSWORD = "NIFI_PASSWORD"
ENV_NIFI_EXTENSIONS_DIR = "NIFI_EXTENSIONS_DIR"
ENV_REGISTRY_ENDPOINT = "REGISTRY_ENDPOINT"
ENV_MESSAGING_MODE = "MESSAGING_MODE"

# Misc
ENV_HF_HUB_OFFLINE = "HF_HUB_OFFLINE"
ENV_HF_HOME = "HF_HOME"
ENV_API_BASE_URL = "API_BASE_URL"
